---
- hosts: repo
  gather_facts: false
  tasks:
    - name: ping the host
      ansible.builtin.ping:
      
    - name: Print OS info
      become: true
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
